### ISSUE TITLE
[BUG] [ERROR] [Renderer]:  TypeError Cannot read properties of null (reading 'provider') TypeError: Cannot read properties of null (reading 'provider')

### ISSUE THREAD

**Issue by Ultra980** [Moosync/Moosync#173]
**Describe the bug**
When I setup moosync, after the folder setup I get a black box above the rest of the ui (where there's supposed to be a part of setup)
**To Reproduce**

1. Open Moosync for the first time (so setup shows up)
2. Click on "begin setup"
3. Click on "next"

**Expected behavior**
The next step of setup should start

**Screenshots**
![image](https://user-images.githubusercontent.com/90788596/204769982-af0c5273-2ab4-47e3-9bbf-3130b1758717.png)

- OS: Linux (openSUSE microOS)
- Version: 5.1.0 (from `flatpak info app.moosync.moosync`)
**Additional context**
Error log:
![image](https://user-images.githubusercontent.com/90788596/204771395-1748f7b1-69b0-4067-8bf9-03d541369149.png)

Somehow, I was able to launch another instance that worked. But idk how to reproduce the success

**Comment by Ovenoboyo** [comment]
Thanks for reporting this issue. It should be fixed in a2df32a6bfb211ec843d51c2b30b6783e202d9ff and be available in the next release :)

**Comment by R-Sharafaldin** [comment]
Error is still reproducible on version 6.0.0.

**Screenshot**
![bilde](https://user-images.githubusercontent.com/45421266/210161062-aabb5e27-06b2-43d9-8cd7-1d44020d7b34.png)


OS: Linux (Fedora 37)
Version: 6.0.0 (from releases, using .rpm)

**Additional context**
Error log:
![bilde](https://user-images.githubusercontent.com/45421266/210161082-257c0036-5ce3-4f7c-a6c2-b6903b5b49fd.png)

**Comment by R-Sharafaldin** [comment]
I was under the impression that 6.0.0 was the next release you were talking about. Taking another look at the commit it is clearly tagged 7.0.0. Tested this under 7.0.0 and the bug is gone. My bad! Works great now.

**Comment by Ovenoboyo** [comment]
I'm glad that its fixed now. I had forgotten to update the version string for Flatpak, which is why it still showed version 6.0.0 as 5.1.0. Sorry for the confusion. 

I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
