### ISSUE TITLE
Crashing instantly on android

### ISSUE THREAD

**Issue by CrossyAtom46** [Moosync/Moosync#33]
[app.moosync.moosync.log](https://github.com/user-attachments/files/21195287/app.moosync.moosync.log)

**Comment by Ovenoboyo** [comment]
I believe the primary error should be fixed in 002e31454d8d81f71d5ebf03839c0362721ac478. I do see various errors, let me know if the build below doesn't work for you

You can find the build here. https://github.com/Moosync/Moosync/actions/runs/16181939436

**Comment by CrossyAtom46** [comment]
Tried and still crashing at the startup.
[app.moosync.moosync.log](https://github.com/user-attachments/files/21203931/app.moosync.moosync.log)

**Comment by CrossyAtom46** [comment]
after giving access to local storage, it fixed, but only for the build you sent. Tried giving storage permission to latest release and still crashing.

BTW tried app on my other phone with latest release, it works fine no issues. (That phone is Android 12, other is Android 9)
